version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hospital-mysql
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - hospital-network
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer:latest
    container_name: hospital-adminer
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    networks:
      - hospital-network

volumes:
  mysql_data:
    driver: local

networks:
  hospital-network:
    driver: bridge
